defmodule BuiltWithPhoenix.Repo.Migrations.AddWeightToOrganizations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organizations) do
      add :weight, :bigint
    end
  end

  def down do
    alter table(:organizations) do
      remove :weight
    end
  end
end
