defmodule BuiltWithPhoenix.Repo.Migrations.AddDescriptionStatusToTechnologyDescriptionToOrganization do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:technologies) do
      add :description, :text
      add :status, :text, default: "new"
    end

    alter table(:organizations) do
      modify :status, :text, default: "new"
      add :description, :text
    end
  end

  def down do
    alter table(:organizations) do
      remove :description
      modify :status, :text, default: nil
    end

    alter table(:technologies) do
      remove :status
      remove :description
    end
  end
end
