defmodule BuiltWithPhoenix.Repo.Migrations.ChangeImageUrlToLogoTechnologies do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:technologies), :image_url, to: :logo

    alter table(:technologies) do
      modify :logo, :text
    end
  end

  def down do
    alter table(:technologies) do
      modify :image_url, :text
    end

    rename table(:technologies), :logo, to: :image_url
  end
end
